#!/bin/bash


if [[ $EUID -ne 0 ]]; then
   echo "Please run as root" 
   exit 1
fi

echo "checking for openVPN"

if dpkg -l | grep openvpn >/dev/null; then
	echo "OpenVPN is installed"
	sleep 1

else
	echo "OpenVPN not found. Installing..."	
	sleep 1
	sudo apt update
	sudo apt install openvpn curl
	echo "OpenVPN installation complete"
	sleep 1
fi

echo "Setting up dirs.."
mkdir /home/pi/.config/nordVPiN/
touch /home/pi/.config/nordVPiN/log.txt
echo "0" > /home/pi/.config/nordVPiN/log.txt
mkdir nord
cd nord
echo "Downloading openVPN server configurations from nordVPN..."
sleep 1
sudo wget https://nordvpn.com/api/files/zip
echo "Unzipping..."
sleep 1
unzip zip


pref="none"
prefsetcorrectly="false"

until [ $prefsetcorrectly = "true" ]
do
	clear
	if [ $pref != "none" ]; then
	 	echo "$pref not valid"
        	echo "Valid codes are: "
		ls *.ovpn | sed 's/.//3g' | uniq | column	       
		read -p 'Please enter prefered connection location(us, uk, de, fr...): ' pref
	
	else
		read -p 'Please enter prefered connection location(us, uk, de, fr...): ' pref
	fi
	
	if [[ $(ls -A $pref*.ovpn | head -c1 | wc -c) -ne 0 ]]
	then
		##user input is a match
		prefsetcorrectly="true"
		echo "Your prefered connection location has been set to: $pref"
		sleep 1
	else
		##user input invalid
		prefsetcorrectly="false"
	fi
done

touch /home/pi/.config/nordVPiN/pref.txt
echo "$pref" > /home/pi/.config/nordVPiN/pref.txt

echo "Adding auto authentication to all configs (may take a few minutes...)"
find -name "*.ovpn" | sudo xargs sed -i '/auth-user-pass/ s/$/ \/etc\/openvpn\/auth.txt/'
touch auth.txt
echo "please provide nordVPN username(email) and Password"
read -p 'Username: ' username
read -sp 'Password: ' password
echo "creating auth.txt"
sleep 1
echo "$username" > auth.txt
echo "$password" >> auth.txt
echo "copying configuration files to openVPN"
sleep 1
find -name "*" | sudo xargs mv -t /etc/openvpn/
cd ..
rm -r nord

echo "Installing scripts..."
sleep 1
cp vpn /usr/local/bin/
cp cronvpn /usr/local/bin
cp proxy /usr/local/bin

echo "Enabling persistence"
sleep 1

if cat /etc/default/openvpn | grep 'AUTOSTART="current"' >/dev/null; then
	echo "Autostart is already configured"
else
	sed -i '15s/.*/AUTOSTART="current"/' /etc/default/openvpn
fi

if crontab -u pi -l | grep 'cronvpn' >/dev/null; then
	echo "crontab entry already exists for 'cronvpn'"

else
	echo "Enabling connection monitoring and auto reconnect"
	sleep 1
	#write out current crontab
	touch tempcron
	crontab -u pi -l > tempcron
	#echo new cron into cron file
	echo "*/5 * * * * sudo /usr/local/bin/cronvpn > /dev/null" >> tempcron
	#install new cron file
	crontab -u pi tempcron
	rm tempcron
fi

echo "Setup complete!"
echo "run 'sudo vpn' to connect to a server from your prefered location, or 'sudo vpn xx' to select country"
echo "eg 'sudo vpn uk' to connect to a United Kingdom server"
