#!/bin/bash

if [[ $EUID -ne 0 ]]; then
	echo "Please run as root"
	exit 1	
fi

case $1 in
	pref)
		if [[ $(ls -A /etc/openvpn/$2*.ovpn | head -c1 | wc -c) -ne 0 ]];then
			##pref is valid
			echo "$2" > /home/pi/.config/nordVPiN/pref.txt
			echo "Prefered connection location updated to $2"
		else
			##pref is invalid
			echo "$2 is not a valid country code"
        		echo "Valid codes are: "
			ls /etc/openvpn/*.ovpn | sed -e 's!.*/!!' -e 's/.//3g' | uniq | column
			echo "Failed to update prefered connection location"
 			exit 1		
		fi
		##update pref with $2
	;;
	*)

ccode=$1
default=$(cat "/home/pi/.config/nordVPiN/pref.txt")
#cserver=$(ls /etc/openvpn/$1* | shuf -n 1)
#defaultserver=$(ls /etc/openvpn/$default* | shuf -n 1)


if [ -z "$ccode" ]

then
	if [[ $(ls -A /etc/openvpn/$default*.ovpn | head -c1 | wc -c) -ne 0 ]]
		then
			##pref is valid
			defaultserver=$(ls /etc/openvpn/$default* | shuf -n 1)
			killall 'openvpn'
			echo "No country given, using prefered: $default"
			echo "Connecting to: $defaultserver"
			sudo openvpn --config "$defaultserver" --daemon
			cp $defaultserver /etc/openvpn/current.conf

		else
			##pref is invalid
			echo "Prefered connection "$default" not valid"
        		echo "Valid codes are: "
			ls /etc/openvpn/*.ovpn | sed -e 's!.*/!!' -e 's/.//3g' | uniq | column

			echo "run 'vpn pref' to update prefered connection"
 			exit 1		
		fi

else
	if [[ $(ls -A /etc/openvpn/$ccode*.ovpn | head -c1 | wc -c) -ne 0 ]]
		then
			##user input is valid
			cserver=$(ls /etc/openvpn/$1* | shuf -n 1)
			killall 'openvpn'
			echo "Connecting to random $ccode server"
			echo "Connecting to: $cserver"
			sudo openvpn --config "$cserver" --daemon
			cp $cserver /etc/openvpn/current.conf

		else
			##user input is invalid
			echo "$ccode not valid"
        		echo "Valid codes are: "
			ls /etc/openvpn/*.ovpn | sed -e 's!.*/!!' -e 's/.//3g' | uniq | column

			exit 1		
		fi
fi

sleep 3
count=1

status=$(curl -s https://nordvpn.com/wp-admin/admin-ajax.php?action=get_user_info_data | sed -n -e 's/^.*status\"://p' | sed 's/.$//')

#echo "$status"
if [ $status == "true" ]; then
	echo "Connected!"
	proxy
	exit 0
else
	until [ $status = "true" ]
       	do
		#repeat this while connection is not esablished
		echo "Checking VPN connection.."
		sleep 3 
		status=$(curl -s https://nordvpn.com/wp-admin/admin-ajax.php?action=get_user_info_data | sed -n -e 's/^.*status\"://p' | sed 's/.$//')
		if (( $count > 5 )); then
			echo "Connection failed"
			exit 1
		else
			#keep trying
			let "count=count+1"
		fi
	done
	echo "Connected!"
fi

proxy
;;
esac
